#!/bin/sh

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

function show_help() {
  cat <<EOF
Usage: $(basename $0) [options] [ -p project_name ] [ -o output_directory ]

Options:
  -h        show this help
  -p        set project name
  -o        output directory
EOF
}

# Initialize our own variables:
project_name=""
output_directory="node"

while getopts "h?p:o:" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    p)  project_name=$OPTARG
        ;;
    o)  output_directory=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

if [ -d $output_directory ]; then
  echo "Output directory already exists!" 1>&2
  exit -1
fi

mkdir -p $output_directory
pushd $output_directory > /dev/null
git init
mkdir -p test

cat <<EOF > app.js
"use strict";

EOF

cat <<EOF > package.json
{
  "name": "$project_name",
  "version": "0.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "node ./node_modules/mocha/bin/mocha -R spec",
    "start": "node ./app.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "mocha": "^2.2.5",
    "should": "^6.0.3"
  },
  "dependencies": {
  },
  "private": true
}
EOF

cat <<EOF > .gitignore
# Logs
logs
*.log

# Runtime data
pids
*.pid
*.seed

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directory
# https://www.npmjs.org/doc/misc/npm-faq.html#should-i-check-my-node_modules-folder-into-git
node_modules
EOF

cat <<EOF > test/template.js
"use strict";

var should = require("should");
/* global it */
/* global before */
/* global describe */

describe("1 + 1", function() {
  var actualOutput;

  before(function(done) {
    actualOutput = 1 + 1;
    done();
  });

  it("equals 2", function() {
	  should(actualOutput).eql(2);
  });
});

EOF

popd > /dev/null

